const DRFM_STANDARD_DATA = {
    assembly: [
        { type: "ASSEMBLY", sub: "", no: 1, desc: "Parts Preparation", ct: 30 },
        { type: "ASSEMBLY", sub: "SEMI-FINISHED", no: 2, desc: "Input Sensor(PCBA Download, Soldering, Assemble)", ct: 30 },
        { type: "ASSEMBLY", sub: "SEMI-FINISHED", no: 3, desc: "Output Sensor(PCBA Download, Soldering, Assemble)", ct: 45 },
        { type: "ASSEMBLY", sub: "SEMI-FINISHED", no: 4, desc: "Sensor Calibration(Input, Output)", ct: 40 },
        { type: "ASSEMBLY", sub: "SUB", no: 5, desc: "PCBA Download", ct: 50 },
        { type: "ASSEMBLY", sub: "SUB", no: 6, desc: "Inductor Measurement", ct: 10 },
        { type: "ASSEMBLY", sub: "SUB", no: 7, desc: "LPF Filter Module", ct: 15 },
        { type: "ASSEMBLY", sub: "SUB", no: 8, desc: "Bandstop Filter Module", ct: 15 },
        { type: "ASSEMBLY", sub: "SUB", no: 9, desc: "VDC Module", ct: 15 },
        { type: "ASSEMBLY", sub: "SUB", no: 10, desc: "VVC Module", ct: 40 },
        { type: "ASSEMBLY", sub: "SUB", no: 11, desc: "VVC Calibration", ct: 30 },
        { type: "ASSEMBLY", sub: "SUB", no: 12, desc: "Front Panel ", ct: 10 },
        { type: "ASSEMBLY", sub: "SUB", no: 13, desc: "Rear Panel", ct: 10 },
        { type: "ASSEMBLY", sub: "SUB", no: 14, desc: "Top Panel", ct: 10 },
        { type: "ASSEMBLY", sub: "SUB", no: 15, desc: "Side Panel", ct: 10 },
        { type: "ASSEMBLY", sub: "MAIN", no: 16, desc: "Output Sensor to Bottom Plate", ct: 15 },
        { type: "ASSEMBLY", sub: "MAIN", no: 17, desc: "Middle Plate", ct: 10 },
        { type: "ASSEMBLY", sub: "MAIN", no: 18, desc: "Input Sensor to Fan Plate", ct: 20 },
        { type: "ASSEMBLY", sub: "MAIN", no: 19, desc: "HF RF Network", ct: 25 },
        { type: "ASSEMBLY", sub: "MAIN", no: 20, desc: "LF RF Network", ct: 25 },
        { type: "ASSEMBLY", sub: "MAIN", no: 21, desc: "PCBA Build to Cable Routing", ct: 60 },
        { type: "ASSEMBLY", sub: "MAIN", no: 22, desc: "PQC", ct: 15 },
        { type: "ASSEMBLY", sub: "MAIN", no: 23, desc: "Enclosure close-up", ct: 30 },
        { type: "ASSEMBLY", sub: "MAIN", no: 24, desc: "Power, I/L Check, temp", ct: 10 },
        { type: "ASSEMBLY", sub: "MAIN", no: 25, desc: "TroubleShooting", ct: 10 }
    ],
    test: [
        { type: "TEST", sub: "BASIC", no: 1, desc: "Preparing Test Report", ct: 5 },
        { type: "TEST", sub: "BASIC", no: 2, desc: "Firmware Verification", ct: 5 },
        { type: "TEST", sub: "BASIC", no: 3, desc: "Visual Inspection", ct: 15 },
        { type: "TEST", sub: "BASIC", no: 4, desc: "Interlock Operation Verification", ct: 10 },
        { type: "TEST", sub: "BASIC", no: 5, desc: "Default Parameters Download", ct: 5 },
        { type: "TEST", sub: "BASIC", no: 6, desc: "Communication Interface Functionality Test", ct: 10 },
        { type: "TEST", sub: "BASIC", no: 7, desc: "Rf Isolation Level Measurement And Adjustment", ct: 15 },
        { type: "TEST", sub: "BASIC", no: 8, desc: "Analog Preset Position Voltage Calibration", ct: 8 },
        { type: "TEST", sub: "BASIC", no: 9, desc: "Analog Position Voltage Calibration", ct: 8 },
        { type: "TEST", sub: "BASIC", no: 10, desc: "Analog VDC Voltage Calibration", ct: 15 },
        { type: "TEST", sub: "BASIC", no: 11, desc: "HF Impedance Range Measurement And Calibration", ct: 20 },
        { type: "TEST", sub: "BASIC", no: 12, desc: "LF Impedance Range Measurement And Calibration", ct: 20 },
        { type: "TEST", sub: "BASIC", no: 13, desc: "HF S-parameters Measurement And Data Collection", ct: 20 },
        { type: "TEST", sub: "BASIC", no: 14, desc: "HF S-parameters Download", ct: 20 },
        { type: "TEST", sub: "BASIC", no: 15, desc: "LF S-parameters Measurement And Data Collection", ct: 20 },
        { type: "TEST", sub: "BASIC", no: 16, desc: "LF S-parameters Download", ct: 20 },
        { type: "TEST", sub: "FINAL", no: 17, desc: "HF Counterload Impedance Measurement And Adjustment", ct: 10 },
        { type: "TEST", sub: "FINAL", no: 18, desc: "MRFS Parameters Setting", ct: 5 },
        { type: "TEST", sub: "FINAL", no: 19, desc: "HF Input Sensor Calibration (include Power Calibration)", ct: 14 },
        { type: "TEST", sub: "FINAL", no: 20, desc: "HF Output Sensor Calibration", ct: 13 },
        { type: "TEST", sub: "FINAL", no: 21, desc: "HF Elite Calibration", ct: 15 },
        { type: "TEST", sub: "FINAL", no: 22, desc: "HF RF Matching Test", ct: 10 },
        { type: "TEST", sub: "FINAL", no: 23, desc: "HF Pulse Matching Test", ct: 8 },
        { type: "TEST", sub: "FINAL", no: 24, desc: "HF Hybrid Matching Test", ct: 8 },
        { type: "TEST", sub: "FINAL", no: 25, desc: "HF Vpp Analog Calibration", ct: 5 },
        { type: "TEST", sub: "FINAL", no: 26, desc: "HF Ethercat Interface Functionality Test", ct: 5 },
        { type: "TEST", sub: "FINAL", no: 27, desc: "LF Counterload Impedance Measurement And Adjustment", ct: 10 },
        { type: "TEST", sub: "FINAL", no: 28, desc: "LF Input Sensor Calibration (include Power Calibration)", ct: 14 },
        { type: "TEST", sub: "FINAL", no: 29, desc: "LF Output Sensor Calibration", ct: 13 },
        { type: "TEST", sub: "FINAL", no: 30, desc: "LF Elite Calibration", ct: 15 },
        { type: "TEST", sub: "FINAL", no: 31, desc: "LF RF Matching Test", ct: 10 },
        { type: "TEST", sub: "FINAL", no: 32, desc: "LF Pulse Matching Test", ct: 8 },
        { type: "TEST", sub: "FINAL", no: 33, desc: "LF Hybrid Matching Test", ct: 8 },
        { type: "TEST", sub: "FINAL", no: 34, desc: "LF Vpp Analog Calibration", ct: 5 },
        { type: "TEST", sub: "FINAL", no: 35, desc: "LF Ethercat Interface Functionality Test", ct: 5 },
        { type: "TEST", sub: "FINAL", no: 36, desc: "HF Parameter Validation", ct: 10 },
        { type: "TEST", sub: "FINAL", no: 37, desc: "LF Parameter Validation", ct: 10 },
        { type: "TEST", sub: "FINAL", no: 38, desc: "Migration Data To Spc Tool", ct: 10 },
        { type: "TEST", sub: "FINAL", no: 39, desc: "Packing", ct: 20 }
    ]
};