const SRFM_STANDARD_DATA = {
    assembly: [
        { type: "ASSEMBLY", sub: "", no: 1, desc: "Parts Preparation", ct: 30 },
        { type: "ASSEMBLY", sub: "SEMI-FINISHED", no: 2, desc: "Input Sensor(PCBA Download, Soldering, Assemble)", ct: 15 },
        { type: "ASSEMBLY", sub: "SEMI-FINISHED", no: 3, desc: "Output Sensor(PCBA Download, Soldering, Assemble)", ct: 15 },
        { type: "ASSEMBLY", sub: "SEMI-FINISHED", no: 4, desc: "Sensor Calibration(Input, Output)", ct: 30 },
        { type: "ASSEMBLY", sub: "SUB", no: 5, desc: "PCBA Download", ct: 10 },
        { type: "ASSEMBLY", sub: "SUB", no: 6, desc: "Inductor Measurement", ct: 10 },
        { type: "ASSEMBLY", sub: "SUB", no: 7, desc: "VVC Module", ct: 20 },
        { type: "ASSEMBLY", sub: "SUB", no: 8, desc: "PCW Cooling Module", ct: 30 },
        { type: "ASSEMBLY", sub: "SUB", no: 9, desc: "Front Panel", ct: 10 },
        { type: "ASSEMBLY", sub: "SUB", no: 10, desc: "Rear Panel", ct: 10 },
        { type: "ASSEMBLY", sub: "SUB", no: 11, desc: "Top Panel", ct: 10 },
        { type: "ASSEMBLY", sub: "SUB", no: 12, desc: "Side Panel", ct: 10 },
        { type: "ASSEMBLY", sub: "MAIN", no: 13, desc: "Output Sensor to Bottom Plate", ct: 10 },
        { type: "ASSEMBLY", sub: "MAIN", no: 14, desc: "Middle Plate", ct: 10 },
        { type: "ASSEMBLY", sub: "MAIN", no: 15, desc: "RF Network", ct: 35 },
        { type: "ASSEMBLY", sub: "MAIN", no: 16, desc: "PCW Cooling", ct: 30 },
        { type: "ASSEMBLY", sub: "MAIN", no: 17, desc: "PCBA Build to Cable Routing", ct: 25 },
        { type: "ASSEMBLY", sub: "MAIN", no: 18, desc: "PQC", ct: 10 },
        { type: "ASSEMBLY", sub: "MAIN", no: 19, desc: "Enclosure close-up", ct: 20 },
        { type: "ASSEMBLY", sub: "MAIN", no: 20, desc: "Power, I/L Check", ct: 10 },
        { type: "ASSEMBLY", sub: "MAIN", no: 21, desc: "Troubleshooting", ct: 10 }
    ],
    test: [
        { type: "TEST", sub: "BASIC", no: 1, desc: "Preparing Test Report", ct: 5 },
        { type: "TEST", sub: "BASIC", no: 2, desc: "Firmware Verification", ct: 5 },
        { type: "TEST", sub: "BASIC", no: 3, desc: "Visual Inspection", ct: 10 },
        { type: "TEST", sub: "BASIC", no: 4, desc: "Interlock Operation Verification", ct: 10 },
        { type: "TEST", sub: "BASIC", no: 5, desc: "Default Parameters Download", ct: 5 },
        { type: "TEST", sub: "BASIC", no: 6, desc: "Communication Interface Functionality Test", ct: 10 },
        { type: "TEST", sub: "BASIC", no: 7, desc: "Analog Preset Position Voltage Calibration", ct: 8 },
        { type: "TEST", sub: "BASIC", no: 8, desc: "Analog Position Voltage Calibration", ct: 8 },
        { type: "TEST", sub: "BASIC", no: 9, desc: "Analog VDC Voltage Calibration", ct: 15 },
        { type: "TEST", sub: "BASIC", no: 10, desc: "HF Impedance Range Measurement And Calibration", ct: 20 },
        { type: "TEST", sub: "BASIC", no: 11, desc: "HF S-parameters Measurement And Data Collection", ct: 20 },
        { type: "TEST", sub: "BASIC", no: 12, desc: "HF S-parameters Download", ct: 20 },
        { type: "TEST", sub: "FINAL", no: 13, desc: "HF Counterload Impedance Measurement And Adjustment", ct: 10 },
        { type: "TEST", sub: "FINAL", no: 14, desc: "MRFS Parameters Setting", ct: 5 },
        { type: "TEST", sub: "FINAL", no: 15, desc: "HF Input Sensor Calibration (include Power Calibration)", ct: 14 },
        { type: "TEST", sub: "FINAL", no: 16, desc: "HF Output Sensor Calibration", ct: 13 },
        { type: "TEST", sub: "FINAL", no: 17, desc: "HF Elite Calibration", ct: 15 },
        { type: "TEST", sub: "FINAL", no: 18, desc: "HF Rf Matching Test", ct: 10 },
        { type: "TEST", sub: "FINAL", no: 19, desc: "HF Pulse Matching Test", ct: 8 },
        { type: "TEST", sub: "FINAL", no: 20, desc: "HF Hybrid Matching Test", ct: 8 },
        { type: "TEST", sub: "FINAL", no: 21, desc: "HF Vpp Analog Calibration", ct: 5 },
        { type: "TEST", sub: "FINAL", no: 22, desc: "HF Ethercat Interface Functionality Test", ct: 5 },
        { type: "TEST", sub: "FINAL", no: 23, desc: "HF Parameter Validation", ct: 10 },
        { type: "TEST", sub: "FINAL", no: 24, desc: "Migration Data To Spc Tool", ct: 10 },
        { type: "TEST", sub: "FINAL", no: 25, desc: "Troubleshooting", ct: 15 },
        { type: "TEST", sub: "FINAL", no: 26, desc: "Packing", ct: 20 }
    ]
};